[build]
builder = "NIXPACKS"
buildCommand = "pip install --upgrade pip && pip install -r requirements_railway.txt"

[deploy]
startCommand = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
healthcheckPath = "/_stcore/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
STREAMLIT_SERVER_PORT = "$PORT"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
PYTHON_VERSION = "3.11"
